### ISSUE TITLE
[Feature] Add support for Brave

### ISSUE THREAD

**Issue by rebelcode-xr** [MacPass/AutotypeURL#10]
Hi and thanks for all your work! 🙏 

I'm trying to use this plugin in order to be able to insert the login directly from **Brave** browser, but I cannot make it working. :( 

Since I've many similar titles if I keep "include Entry Title for matches" that would **load the wrong entry**, so I though to disable it and keep only the "include Entry URL for matches" option:
![image](https://user-images.githubusercontent.com/63522951/94264083-5b1a7980-ff36-11ea-8baf-ca7a78dff1d1.png)

In order to make it working download and installed the plugin to read the url from the browser:
![image](https://user-images.githubusercontent.com/63522951/94264255-ac2a6d80-ff36-11ea-9c40-1ad32d778ee7.png)

Sadly when I press the hotkey, nothing happens... 😢 
Am I doing something wrong?

**Comment by rebelcode-xr** [comment]
UPDATE
I have tried with Safari and it works: It seems that Brave is not supported

**Comment by mstarke** [comment]
I took the liberty to re-name the issue into a feature request.

**Comment by jasonlyle88** [comment]
Id like to mimic the OP in thanking you for your great work on this entire project!

I'd love to see this request extended beyond Brave. It would be great to see all the major browsers included here. Not sure how big of an effort this is (in both initial development and then maintenance), so maybe it isn't feasible to support a large browser set. But would still like to request and find out if it is feasible! Brave, as mentioned above, but also edge, firefox, and possibly even opera and tor browser (may be same implementation as firefox). As a web developer, I frequently need to test against multiple browsers. Having this just work whenever I'm jumping around would be great!

**Comment by rebelcode-xr** [comment]
> I took the liberty to re-name the issue into a feature request.

That's perfect, thank you! 🙏

**Comment by rebelcode-xr** [comment]
Should be just needed to change "com.google.Chrome" into "com.brave.browser" (creating a new ATUBraveExtractor.m file of course).
https://github.com/MacPass/AutotypeURL/blob/master/AutotypeURL/ATUChromeExtractor.m

maybe a different approach could make easier to add a list of browsers, like here:
https://github.com/johnste/finicky/blob/master/Finicky/Finicky/Browsers.swift

**Comment by mstarke** [comment]
@rebelcode-xr added support for Brave in 1.1. Also the system now allows for lists of bundle identifiers not just a single one per extractor so it should be easily expandable for chrome-like browsers.

**Comment by rebelcode-xr** [comment]
> @rebelcode-xr added support for Brave in 1.1. Also the system now allows for lists of bundle identifiers not just a single one per extractor so it should be easily expandable for chrome-like browsers.

amazing! 😄 waiting the compiled version 🙏

**Comment by rebelcode-xr** [comment]
tested it: **awesome**!!! 🥳

**Comment by rebelcode-xr** [comment]
PS
remember to update the supported browsers list ;)
