### ISSUE TITLE
[Feature] Add support for Firefox

### ISSUE THREAD

**Issue by rebelcode-xr** [MacPass/AutotypeURL#11]
Like for #10 would be great to add also Firefox support! ;)

**Comment by mstarke** [comment]
Firefox seems to be a bit tricky since I haven't been able to query the URL via Apple Script. It might be necessary to rely on accessibly to get the URL extracted.

**Comment by georgesnow** [comment]
I can take a look at Firefox. I had tested Firefox when I first worked on the plug-in. And I remember there were some variation compare to other browsers (Chrome and safari)

**Comment by rburgst** [comment]
Any updates?
