### ISSUE TITLE
Apple M1 support

### ISSUE THREAD

**Issue by IanAtSalt** [MacPass/AutotypeURL#14]
Trying to load this in BigSur on M1 Mac shows not available for my architecture

**Comment by georgesnow** [comment]
So there isn’t compiled universal binary for M1 yet. I had some issues building it for M1 as there is some changes upstream. 

You can build your own and locally sign it. It wasn’t easy. On the main macpass repo there is an Issue about plugins that I go through how I did it.

**Comment by mstarke** [comment]
Fixed with 1.3
