### ISSUE TITLE
applescript modification for firefox

### ISSUE THREAD

**Issue by georgesnow** [MacPass/AutotypeURL#16]
instead of using system events and relying on synthetic keyboard action. if you use the applescript below:

````applescript
tell application "Firefox"
	get name of front window
	
end tell
````

 in conjunction with this extension:
https://addons.mozilla.org/en-US/firefox/addon/keepass-helper-url-in-title/

I think it might be a bit more reliable.

**Comment by mstarke** [comment]
This seems like a nice idea but adds a third component to the mix so I'm a bit hesitant to introduce this change. We might have to extend the Settings to allow for custom behaviour based on the browser which would allow to show an information box on what to do for each supported browser (e.g. install said extension on Firefox)

**Comment by georgesnow** [comment]
Agreed. I only mentioned it because with using system events if focus of the app is lost. Another app activates due to a prompt or notification. The behavior maybe not be reliable in what text it grabs.
