### ISSUE TITLE
[Bug] Toggling doesn't change preferences

### ISSUE THREAD

**Issue by georgesnow** [MacPass/AutotypeURL#8]
my initial testing when I toggle between full and host. It only uses the host. I tried closing the app and re-opening MacPass. I will need to do some more thorough testing to make sure its not my setup.

**Comment by mstarke** [comment]
Crap. I did only look at the prefs via defaults read. I might have broken something.

**Comment by mstarke** [comment]
If this is fixed I plan to release the plugin officially and MacPass 0.7.10 should follow shortly.

**Comment by georgesnow** [comment]
a quick look, I think I found it. I might be able to fix it real quick

**Comment by georgesnow** [comment]
never mind, so this is a weird. the correct string is getting passed for the url as the window title, but MacPass matches entries based just on the host name not the full URL even though the full string is being sent.

**Comment by georgesnow** [comment]
Example:
Entry A - keepass.info
Entry B - https://keepass.info/help/kb/testform.html

URL String from plugin:
https://keepass.info/help/kb/testform.html
 
Expected Match just B

Actual Matches entries A and B

**Comment by mstarke** [comment]
Your example is completely correct. Autotype matches if the title of an entry is contained in the window title which is true for both. If you want more fine grain URL matching you probably want to use the URL field of entries and tune the match strings in MacPass. Another approach is to use window associations which allow for even more customization.

**Comment by georgesnow** [comment]
Ok just to clarify those URLs are in the URL field of their respective entries. I did try turning on and off the 2 url options in integration settings for AutotypeURL but that didn’t yield better any better results. 
Am I misunderstanding what I need to tweak?

**Comment by georgesnow** [comment]
Correction not the AutotypeURL. The global auto type settings in MacPass.

**Comment by mstarke** [comment]
If you only tick URL matching and not URL Host matching, then MacPass should yield only match B from your example when AutotypeURL is returning the full URL

**Comment by georgesnow** [comment]
@mstarke ok cool that makes sense. so from my tests show that its not matching for the full url. And i tested with string getting printed to the console and it shows the full string:

https://keepass.info/help/kb/testform.html



![mp-entries](https://user-images.githubusercontent.com/12751441/63438733-d2f4a700-c3fa-11e9-892f-7f4d34cdee90.png)
![mp-nomatch](https://user-images.githubusercontent.com/12751441/63438774-e6077700-c3fa-11e9-809a-7a8da163159b.png)

![mp-settings](https://user-images.githubusercontent.com/12751441/63438657-afc9f780-c3fa-11e9-9dd3-05e78a35ad38.png)
![atu-settings](https://user-images.githubusercontent.com/12751441/63438666-b193bb00-c3fa-11e9-9b6b-143e793e0ec7.png)

**Comment by georgesnow** [comment]
@mstarke never mind i figured it out by tweaking the settings. so i am going to close this. i haven't found any other bugs/
